/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallervistas;

import java.sql.Date;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import tallerdereparaciones.Aparato;
import tallerdereparaciones.AparatoData;
import tallerdereparaciones.Cliente;
import tallerdereparaciones.ClienteData;
import tallerdereparaciones.Conexion;
import tallerdereparaciones.ReparacionesData;
import tallerdereparaciones.Servicio;
import tallerdereparaciones.ServicioData;

/**
 *
 * @author SilZitoS
 */
public class JIFBusqueda extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFBusqueda
     */
    
    private Conexion conexion;
    private AparatoData ad;
    private ServicioData sd;
    private ReparacionesData rd;
    private DefaultTableModel modelo;
    
    
    public JIFBusqueda() {
        initComponents();
        try {
            conexion = new Conexion();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JIFBusqueda.class.getName()).log(Level.SEVERE, null, ex);
        }
        ad= new AparatoData(conexion);
        List<Aparato> la = ad.obtenerAparatos();
        for (Aparato c:la){
            jcDueño.addItem(c.getDueño());
        }
        sd = new ServicioData(conexion);
        List<Servicio> ls = sd.obtenerServicios();
        for (Servicio s:ls){
            jcServicio.addItem(s.getDescripcion());
        }
        for (Aparato a:la){
            jcIngreso.addItem((Date) a.getFechaIngreso());
        }
        
        modelo=new DefaultTableModel();
        rd=new ReparacionesData(conexion);
        armarCabeceraTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jcDueño = new javax.swing.JComboBox<>();
        jcServicio = new javax.swing.JComboBox<>();
        jcIngreso = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAparatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbSalir = new javax.swing.JButton();
        jbBusquedaDueño = new javax.swing.JButton();
        jbBusquedaServicio = new javax.swing.JButton();
        jbBusquedaFechaIngreso = new javax.swing.JButton();

        jcDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcDueñoActionPerformed(evt);
            }
        });

        jcServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcServicioActionPerformed(evt);
            }
        });

        jcIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcIngresoActionPerformed(evt);
            }
        });

        tAparatos.setForeground(new java.awt.Color(153, 0, 153));
        tAparatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tAparatos);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Por Dueño:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Por Servicio:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Por Fecha de Ingreso:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 204));
        jLabel4.setText("Busqueda Avanzada de Aparatos");

        jbSalir.setText("Finalizar");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbBusquedaDueño.setText("Buscar");
        jbBusquedaDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBusquedaDueñoActionPerformed(evt);
            }
        });

        jbBusquedaServicio.setText("Buscar");
        jbBusquedaServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBusquedaServicioActionPerformed(evt);
            }
        });

        jbBusquedaFechaIngreso.setText("Buscar");
        jbBusquedaFechaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBusquedaFechaIngresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcDueño, 0, 284, Short.MAX_VALUE)
                                    .addComponent(jcIngreso, 0, 284, Short.MAX_VALUE)
                                    .addComponent(jcServicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbBusquedaServicio)
                                    .addComponent(jbBusquedaDueño)
                                    .addComponent(jbBusquedaFechaIngreso)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(268, 268, 268)
                                .addComponent(jbSalir))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel4)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbBusquedaDueño))
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBusquedaServicio))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBusquedaFechaIngreso))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbSalir)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jcDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcDueñoActionPerformed
        
    }//GEN-LAST:event_jcDueñoActionPerformed

    private void jcServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcServicioActionPerformed

    }//GEN-LAST:event_jcServicioActionPerformed

    private void jcIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcIngresoActionPerformed

    }//GEN-LAST:event_jcIngresoActionPerformed

    private void jbBusquedaDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBusquedaDueñoActionPerformed
        cargaDatosPorDueño();
    }//GEN-LAST:event_jbBusquedaDueñoActionPerformed

    private void jbBusquedaServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBusquedaServicioActionPerformed
        cargaDatosPorServicio();
    }//GEN-LAST:event_jbBusquedaServicioActionPerformed

    private void jbBusquedaFechaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBusquedaFechaIngresoActionPerformed
        cargaDatosPorFechaIngreso();
    }//GEN-LAST:event_jbBusquedaFechaIngresoActionPerformed

    public void armarCabeceraTabla(){
        //Titulo de Columnas
        ArrayList<Object> columnas=new ArrayList<Object>();
        columnas.add("ID");
        columnas.add("Nº de Serie");
        columnas.add("Tipo");
        columnas.add("Dueño");
        columnas.add("F. de Ingreso");
        columnas.add("F. de Egreso");
        
        for(Object it:columnas){
            modelo.addColumn(it);
        }
        tAparatos.setModel(modelo);
    }
    
    public void borrarFilas(){
        int a = modelo.getRowCount()-1;
        for (int i=a; i>=0; i--){
            modelo.removeRow(i);
        }
    }
    
    public void cargaDatosPorFechaIngreso(){
        borrarFilas();
        Date d = (Date)jcIngreso.getSelectedItem();
        rd = new ReparacionesData(conexion);
        List<Aparato> lAparatos = rd.buscarAparatosPorFechaIngreso(d);
        for(Aparato a : lAparatos){
                modelo.addRow(new Object[]{a.getIdAparato(), a.getNroSerie(), a.getTipo(), a.getDueño(), a.getFechaIngreso(), a.getFechaEgreso()});
        }
    }
    
    public void cargaDatosPorDueño(){
        borrarFilas();
        Cliente c = (Cliente)jcDueño.getSelectedItem();
        int i=c.getIdCliente();
        rd = new ReparacionesData(conexion);
        List<Aparato> listaAparatos = rd.buscarAparatosPorDueño(i);
        for(Aparato a : listaAparatos){
                modelo.addRow(new Object[]{a.getIdAparato(), a.getNroSerie(), a.getTipo(), a.getDueño(), a.getFechaIngreso(), a.getFechaEgreso()});
        }
    }
    
    public void cargaDatosPorServicio(){
        borrarFilas();
        rd = new ReparacionesData(conexion);
        String d=(String)jcServicio.getSelectedItem();
        Servicio s=sd.buscarServicioPorDescripcion(d);
        List<Aparato> listaAparatos = rd.buscarAparatosPorServicio(s.getIdServicio());
        for(Aparato a : listaAparatos){
                modelo.addRow(new Object[]{a.getIdAparato(), a.getNroSerie(), a.getTipo(), a.getDueño(), a.getFechaIngreso(), a.getFechaEgreso()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBusquedaDueño;
    private javax.swing.JButton jbBusquedaFechaIngreso;
    private javax.swing.JButton jbBusquedaServicio;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Cliente> jcDueño;
    private javax.swing.JComboBox<Date> jcIngreso;
    private javax.swing.JComboBox<String> jcServicio;
    private javax.swing.JTable tAparatos;
    // End of variables declaration//GEN-END:variables
}
